# Generated by Django 2.0.3 on 2018-03-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ally',
            fields=[
                ('ally_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ally_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('personality', models.CharField(max_length=200)),
                ('traits', models.CharField(max_length=200)),
                ('last_edit', models.DateTimeField(verbose_name='date editted')),
                ('img_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('attr_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('sheet_id', models.IntegerField(default=0)),
                ('attribute_name', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=0)),
                ('temp_value', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dm',
            fields=[
                ('dm_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dm_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=1000)),
                ('importance', models.IntegerField(default=0)),
                ('last_edit', models.DateTimeField(verbose_name='date editted')),
                ('img_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('decription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dm_id', models.IntegerField(default=0)),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('sheet_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(default=0)),
                ('character_name', models.CharField(max_length=200)),
            ],
        ),
    ]
