# Generated by Django 2.0.3 on 2018-03-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
