# Generated by Django 2.0.3 on 2018-03-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0002_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=1000)),
                ('importance', models.IntegerField(default=0)),
                ('last_edit', models.DateTimeField(verbose_name='date editted')),
                ('img_url', models.CharField(max_length=300)),
            ],
        ),
    ]
