# Generated by Django 2.0.3 on 2018-04-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='decription',
            new_name='description',
        ),
    ]
