# Generated by Django 2.0.3 on 2018-04-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0005_auto_20180401_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levels',
            name='dm_id',
            field=models.IntegerField(default=0),
        ),
    ]
