# Generated by Django 2.0.3 on 2018-04-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0007_auto_20180401_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allies',
            name='ally_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='attr_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sheets',
            name='sheet_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
