# Generated by Django 2.0.3 on 2018-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0008_auto_20180401_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allies',
            name='ally_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='attr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dm',
            name='dm_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sheets',
            name='sheet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
