# Generated by Django 2.0.3 on 2018-04-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0009_auto_20180401_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='decription',
            new_name='description',
        ),
    ]
