# Generated by Django 2.0.3 on 2018-04-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0010_auto_20180402_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='item_name',
        ),
    ]
