# Generated by Django 2.0.3 on 2018-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmeditor', '0013_ally_mapping_item_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ally_mapping',
            name='given_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
